name: ffmpeg
run-name: ${{ github.workflow }} ✅ ${{ github.event_name}}
on:
  workflow_call:
      outputs:
       ffmpeg_outcome:
        description: "jobs.ffmpeg.outputs.output_ffmpeg"
        value: ${{ jobs.ffmpeg.outputs.output_ffmpeg }}

  workflow_dispatch:
  pull_request_target:
    branches: 'main'
    types: [closed]

jobs:
  grabbed:
    runs-on: ubuntu-latest
    continue-on-error: false
    defaults:
      run:
        working-directory: ./hls
    outputs:
      output_ffmpeg: ${{ steps.ffmpeg_outcome.outputs.ffmpeg_outcome}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installing
        run: |
         sudo apt-get update && sudo apt-get install -y ffmpeg
        shell: bash

      - name: Converter
        id: ffmpeg
        run: |
          ffmpeg -loop 1 -i ./content/expired.png -i ./content/expired.m4a -c:v libx265 -tune stillimage -c:a copy -pix_fmt yuv420p -shortest -hls_list_size 0 ./content/expired.mp4
          ffmpeg -threads 0 -i ./content/expired.mp4 -r 24 -g 48 -keyint_min 48 -sc_threshold 0 -c:v libx265 -s:v:0 960x540 -b:v:0 2400k -maxrate:v:0 2640k -bufsize:v:0 2400k -s:v:1 1920x1080 -b:v:1 5200k -maxrate:v:1 5720k -bufsize:v:1 5200k -s:v:2 1280x720 -b:v:2 3100k -maxrate:v:2 3410k -bufsize:v:2 3100k -s:v:3 640x360 -b:v:3 1200k -maxrate:v:3 1320k -bufsize:v:3 1200k -b:a 128k -ar 44100 -ac 2 -map 0:v -map 0:v -map 0:v -map 0:v -map 0:a -f hls -var_stream_map "v:0,agroup:audio v:1,agroup:audio v:2,agroup:audio v:3,agroup:audio a:0,agroup:audio" -hls_flags single_file -hls_segment_type fmp4 -hls_list_size 0 -hls_time 6 -master_pl_name index.m3u8 -y ./expired/index_%v.m3u8
        shell: bash

      - name: Outcome
        id: ffmpeg_outcome
        run: |
         echo ${{ github.event_name }}
         echo ${{ steps.ffmpeg.outcome }}
         echo "ffmpeg_outcome=${{ steps.ffmpeg.outcome }}" >> $GITHUB_OUTPUT
          
      - name: Deploy
        if: ${{ github.event_name == 'workflow_dispatch' }} || ${{ github.event_name == 'schedule' }}
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}
          git pull
          git add ./expired/*
          git commit -m "ffmpeg - ${{ steps.ffmpeg.outcome }}"
          git push
          
