name: tempest
run-name: ${{ github.workflow }} ✅ ${{ github.event_name}}
on:
  workflow_call:
      outputs:
       tempest_outcome:
        description: "jobs.tempest.outputs.output_tempest"
        value: ${{ jobs.tempest.outputs.output_tempest }}

  workflow_dispatch:
  pull_request_target:
    branches: 'main'
    types: [closed]
  schedule:
  - cron: '0 17 * * *'

jobs:
  tempest:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    continue-on-error: false
    strategy:

      max-parallel: 2
    defaults:
      run:
        working-directory: ./tempest
    outputs:
      output_tempest: ${{ steps.tempest_outcome.outputs.tempest_outcome}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installing
        run: sudo apt-get update && sudo apt-get install -y php
        shell: bash

      - name: Tempest
        id: tempest
        run: |
          php ./tempest.php engine=Generate tempconfig=dummy.config.xml
          # php ./tempest.php engine=Generate tempconfig=tempest.config.xml
          cp -f ./tempest_config/epg/dummy.xml ./guide/expired.xml
          # cp -f ./tempest_config/epg/guide.xml ./guide/guide.xml
        shell: bash

      - name: Outcome
        id: tempest_outcome
        run: |
         echo ${{ github.event_name }}
         echo ${{ steps.tempest.outcome }}
         echo "tempest_outcome=${{ steps.tempest.outcome }}" >> $GITHUB_OUTPUT
          
      - name: Deploy
        if: ${{ github.event_name == 'workflow_dispatch' }} || ${{ github.event_name == 'schedule' }}
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}
          git pull
          git add ./guide/expired.xml
          # git add ./guide/guide.xml
          git commit -m "tempest - ${{ steps.tempest.outcome }}"
          git push
